In [1]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [4]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 11:23:37) [Clang 14.0.6 ]'

In [6]:
my_list = [0, 1, 2, 3, 4, 5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [8]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
#np.

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(3.0)

array([0., 1., 2.])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(20, 10) # 1st arg < 2nd arg

array([], dtype=int64)

In [18]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [19]:
np.arange(-20, -10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [20]:
np.arange(30, 20)

array([], dtype=int64)

In [21]:
ar = np.arange(-30, 20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [22]:
np.arange(10, 10)

array([], dtype=int64)

In [23]:
np.arange()

TypeError: arange() requires stop to be specified.

In [24]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [25]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [26]:
np.arange(10, 30, 5, 8)

TypeError: Cannot interpret '8' as a data type

In [28]:
np.zeros(3) # parameter  tunning 

array([0., 0., 0.])

In [30]:
np.zeros(5, dtype=int) # hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [35]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [36]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [37]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [39]:
np.zeros((2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.zeros((10, 30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [44]:
np.zeros((5, 10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
n = (6,7)
n1 = (7, 8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [46]:
print(np.zeros(n, dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [49]:
np.ones(3)

array([1., 1., 1.])

In [50]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [51]:
np.ones(4)

array([1., 1., 1., 1.])

In [52]:
n

(6, 7)

In [53]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [55]:
np.ones((5, 4), dtype=int)  # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [56]:
np.two(2, 2)

AttributeError: module 'numpy' has no attribute 'two'

In [58]:
np.three(2, 3)

AttributeError: module 'numpy' has no attribute 'three'

In [59]:
np.ones(2)

array([1., 1.])

In [60]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
np.ones((6, 10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [62]:
range(5)

range(0, 5)

In [64]:
r = range(5)
r

range(0, 5)

In [66]:
for i in r:
    print(i)

0
1
2
3
4


In [67]:
list(range(5))

[0, 1, 2, 3, 4]

In [69]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [70]:
rand(3, 2)

NameError: name 'rand' is not defined

In [71]:
random.rand(3, 2)

NameError: name 'random' is not defined

In [72]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [73]:
np.random.rand(5)

array([0.68541176, 0.31367347, 0.89833213, 0.03033295, 0.04156242])

In [74]:
np.random.rand(2, 4)

array([[0.9235488 , 0.1747095 , 0.98635783, 0.02936352],
       [0.45237858, 0.36070998, 0.98999156, 0.98453017]])

In [76]:
np.random.randint(2, 4)

2

In [79]:
np.random.randint(2, 20) # 2nd argument is exlusive 

10

In [80]:
np.random.randint(0, 1)

0

In [81]:
np.random.randint(10, 20, 5)

array([18, 14, 19, 14, 12])

In [82]:
np.random.randint(1, 6, 4)

array([5, 5, 4, 2])

In [83]:
np.random.rand(3)

array([0.39647443, 0.67344991, 0.50881198])

In [103]:
np.random.randint(1)

0

In [104]:
np.random.randint(30, 20, 10)

ValueError: low >= high

In [105]:
np.random.randint(-30, 20, 10)

array([  2,  19, -25,  13, -26,  -7, -30,  -4,  12,   3])

In [106]:
np.random.randint(20, 30, 10)

array([22, 23, 21, 24, 25, 22, 20, 29, 24, 27])

In [107]:
np.random.randint(10, 21, 3)

array([14, 19, 19])

In [108]:
np.random.randint(1, 12, 10)

array([1, 5, 4, 5, 8, 8, 6, 2, 4, 8])

In [109]:
np.random.randint(10, 40, (10, 10))

array([[15, 39, 24, 19, 18, 30, 14, 34, 32, 25],
       [25, 22, 28, 33, 21, 28, 17, 34, 19, 31],
       [36, 28, 28, 30, 13, 32, 26, 30, 16, 28],
       [16, 17, 19, 28, 34, 15, 18, 25, 28, 27],
       [39, 12, 29, 22, 33, 24, 26, 12, 28, 39],
       [19, 14, 12, 22, 19, 26, 31, 37, 28, 18],
       [16, 18, 30, 17, 25, 20, 34, 12, 12, 19],
       [14, 38, 30, 22, 28, 26, 28, 21, 26, 13],
       [27, 10, 27, 20, 18, 37, 24, 23, 32, 18],
       [14, 36, 19, 27, 27, 10, 34, 13, 34, 14]])

In [110]:
np.random.randint(1, 100, (12, 12))

array([[17, 53, 64, 10, 23, 22, 89, 93, 79, 92, 83, 24],
       [70, 60,  8, 41, 59, 94, 11, 37, 70, 24, 90, 93],
       [21, 73, 92, 15, 46, 31, 42, 91,  7, 90, 50, 95],
       [35, 18, 53, 19, 76, 64, 65, 74,  2, 64, 10, 80],
       [80, 39, 49, 35,  7, 96,  7, 23, 70, 93, 17, 55],
       [48, 85, 71, 92, 66, 85, 85, 79, 10, 39, 42, 40],
       [73, 72, 76, 49, 29, 98, 59, 31, 48, 72, 69,  3],
       [64, 78, 44, 92, 40, 76, 84, 33, 10, 94, 95,  8],
       [20, 30, 27, 34, 89, 75, 44, 24, 88, 85, 72,  6],
       [21, 43, 92, 17, 89, 90, 48, 71, 86, 73, 21, 62],
       [96, 91, 49, 67,  8, 57, 62, 94,  8, 43, 52, 53],
       [50,  1, 60, 43,  8, 75, 37, 34, 68, 59, 55, 45]])

In [113]:
np.arange(1, 13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
np.arange(1, 13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [116]:
b = np.random.randint(10, 20, (5, 4))
b

array([[12, 18, 12, 12],
       [14, 19, 11, 16],
       [19, 17, 16, 12],
       [17, 16, 17, 13],
       [10, 19, 11, 19]])

In [117]:
type(b)

numpy.ndarray

In [118]:
b[:]

array([[12, 18, 12, 12],
       [14, 19, 11, 16],
       [19, 17, 16, 12],
       [17, 16, 17, 13],
       [10, 19, 11, 19]])

In [119]:
b[1:3]

array([[14, 19, 11, 16],
       [19, 17, 16, 12]])

In [123]:
b[1,2]

np.int64(11)

In [124]:
print(b[1,2])

11


In [125]:
b

array([[12, 18, 12, 12],
       [14, 19, 11, 16],
       [19, 17, 16, 12],
       [17, 16, 17, 13],
       [10, 19, 11, 19]])

In [126]:
b[1, 3]

np.int64(16)

In [128]:
b[1,-1]

np.int64(16)

In [129]:
b[2:3]

array([[19, 17, 16, 12]])

In [130]:
b

array([[12, 18, 12, 12],
       [14, 19, 11, 16],
       [19, 17, 16, 12],
       [17, 16, 17, 13],
       [10, 19, 11, 19]])

In [131]:
b[0:-2]

array([[12, 18, 12, 12],
       [14, 19, 11, 16],
       [19, 17, 16, 12]])

In [132]:
b[0, 2]

np.int64(12)

In [133]:
b

array([[12, 18, 12, 12],
       [14, 19, 11, 16],
       [19, 17, 16, 12],
       [17, 16, 17, 13],
       [10, 19, 11, 19]])

In [134]:
b[-5, -3]

np.int64(18)

In [135]:
b[-4, 2]

np.int64(11)

In [137]:
np.random.randint(10, 20, (4, 4))

array([[16, 13, 10, 12],
       [11, 14, 16, 14],
       [10, 19, 11, 14],
       [14, 17, 17, 10]])

In [138]:
b

array([[12, 18, 12, 12],
       [14, 19, 11, 16],
       [19, 17, 16, 12],
       [17, 16, 17, 13],
       [10, 19, 11, 19]])

In [140]:
b[-4,-2]

np.int64(11)

In [141]:
b[-4:-2]

array([[14, 19, 11, 16],
       [19, 17, 16, 12]])

In [142]:
b[:]

array([[12, 18, 12, 12],
       [14, 19, 11, 16],
       [19, 17, 16, 12],
       [17, 16, 17, 13],
       [10, 19, 11, 19]])

## Operations

In [143]:
a = np.random.randint(10, 20, 10)
a

array([16, 11, 12, 12, 16, 12, 16, 14, 13, 10])

In [144]:
id(a)

4668994256

In [145]:
arr

array([0, 1, 2, 3, 4, 5])

In [147]:
arr2 = np.random.randint(0, 100, (10, 10))
arr2

array([[18, 53,  0, 59, 88, 70,  1, 66, 34, 61],
       [19, 40, 38,  0, 48, 61, 47, 88, 35, 69],
       [24, 41, 95, 75,  2,  1, 22, 76, 93, 83],
       [53,  5, 42, 58, 14, 36, 66, 43,  3, 55],
       [90, 51, 19, 16, 94, 69, 77, 38, 85, 26],
       [29,  3, 64, 32, 75, 81, 47, 64, 66, 38],
       [80, 82, 13,  7, 86,  1, 27, 80, 91, 92],
       [80, 35, 90, 41, 12, 84, 88, 38, 28, 20],
       [52,  6, 33, 72,  1, 19, 86, 60, 89,  9],
       [12, 64, 18, 81, 82, 14, 29, 36, 35, 33]])

In [148]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [149]:
arr[:4]

array([0, 1, 2, 3])

In [150]:
arr[2:]

array([2, 3, 4, 5])

In [151]:
arr[:4]

array([0, 1, 2, 3])

In [152]:
arr2[:]

array([[18, 53,  0, 59, 88, 70,  1, 66, 34, 61],
       [19, 40, 38,  0, 48, 61, 47, 88, 35, 69],
       [24, 41, 95, 75,  2,  1, 22, 76, 93, 83],
       [53,  5, 42, 58, 14, 36, 66, 43,  3, 55],
       [90, 51, 19, 16, 94, 69, 77, 38, 85, 26],
       [29,  3, 64, 32, 75, 81, 47, 64, 66, 38],
       [80, 82, 13,  7, 86,  1, 27, 80, 91, 92],
       [80, 35, 90, 41, 12, 84, 88, 38, 28, 20],
       [52,  6, 33, 72,  1, 19, 86, 60, 89,  9],
       [12, 64, 18, 81, 82, 14, 29, 36, 35, 33]])

In [153]:
arr2[0:5]

array([[18, 53,  0, 59, 88, 70,  1, 66, 34, 61],
       [19, 40, 38,  0, 48, 61, 47, 88, 35, 69],
       [24, 41, 95, 75,  2,  1, 22, 76, 93, 83],
       [53,  5, 42, 58, 14, 36, 66, 43,  3, 55],
       [90, 51, 19, 16, 94, 69, 77, 38, 85, 26]])

In [155]:
print(arr2[1, 4])

48


In [159]:
print(arr2[-5,5])

81


In [158]:
print(arr2[-5,-5])

81


In [160]:
arr2

array([[18, 53,  0, 59, 88, 70,  1, 66, 34, 61],
       [19, 40, 38,  0, 48, 61, 47, 88, 35, 69],
       [24, 41, 95, 75,  2,  1, 22, 76, 93, 83],
       [53,  5, 42, 58, 14, 36, 66, 43,  3, 55],
       [90, 51, 19, 16, 94, 69, 77, 38, 85, 26],
       [29,  3, 64, 32, 75, 81, 47, 64, 66, 38],
       [80, 82, 13,  7, 86,  1, 27, 80, 91, 92],
       [80, 35, 90, 41, 12, 84, 88, 38, 28, 20],
       [52,  6, 33, 72,  1, 19, 86, 60, 89,  9],
       [12, 64, 18, 81, 82, 14, 29, 36, 35, 33]])

In [161]:
arr2[-1, -2]

np.int64(35)

In [162]:
arr2[::-1]

array([[12, 64, 18, 81, 82, 14, 29, 36, 35, 33],
       [52,  6, 33, 72,  1, 19, 86, 60, 89,  9],
       [80, 35, 90, 41, 12, 84, 88, 38, 28, 20],
       [80, 82, 13,  7, 86,  1, 27, 80, 91, 92],
       [29,  3, 64, 32, 75, 81, 47, 64, 66, 38],
       [90, 51, 19, 16, 94, 69, 77, 38, 85, 26],
       [53,  5, 42, 58, 14, 36, 66, 43,  3, 55],
       [24, 41, 95, 75,  2,  1, 22, 76, 93, 83],
       [19, 40, 38,  0, 48, 61, 47, 88, 35, 69],
       [18, 53,  0, 59, 88, 70,  1, 66, 34, 61]])

In [163]:
arr2

array([[18, 53,  0, 59, 88, 70,  1, 66, 34, 61],
       [19, 40, 38,  0, 48, 61, 47, 88, 35, 69],
       [24, 41, 95, 75,  2,  1, 22, 76, 93, 83],
       [53,  5, 42, 58, 14, 36, 66, 43,  3, 55],
       [90, 51, 19, 16, 94, 69, 77, 38, 85, 26],
       [29,  3, 64, 32, 75, 81, 47, 64, 66, 38],
       [80, 82, 13,  7, 86,  1, 27, 80, 91, 92],
       [80, 35, 90, 41, 12, 84, 88, 38, 28, 20],
       [52,  6, 33, 72,  1, 19, 86, 60, 89,  9],
       [12, 64, 18, 81, 82, 14, 29, 36, 35, 33]])

In [164]:
arr2[::-2]

array([[12, 64, 18, 81, 82, 14, 29, 36, 35, 33],
       [80, 35, 90, 41, 12, 84, 88, 38, 28, 20],
       [29,  3, 64, 32, 75, 81, 47, 64, 66, 38],
       [53,  5, 42, 58, 14, 36, 66, 43,  3, 55],
       [19, 40, 38,  0, 48, 61, 47, 88, 35, 69]])

In [165]:
arr2

array([[18, 53,  0, 59, 88, 70,  1, 66, 34, 61],
       [19, 40, 38,  0, 48, 61, 47, 88, 35, 69],
       [24, 41, 95, 75,  2,  1, 22, 76, 93, 83],
       [53,  5, 42, 58, 14, 36, 66, 43,  3, 55],
       [90, 51, 19, 16, 94, 69, 77, 38, 85, 26],
       [29,  3, 64, 32, 75, 81, 47, 64, 66, 38],
       [80, 82, 13,  7, 86,  1, 27, 80, 91, 92],
       [80, 35, 90, 41, 12, 84, 88, 38, 28, 20],
       [52,  6, 33, 72,  1, 19, 86, 60, 89,  9],
       [12, 64, 18, 81, 82, 14, 29, 36, 35, 33]])

In [166]:
arr2[::-3]

array([[12, 64, 18, 81, 82, 14, 29, 36, 35, 33],
       [80, 82, 13,  7, 86,  1, 27, 80, 91, 92],
       [53,  5, 42, 58, 14, 36, 66, 43,  3, 55],
       [18, 53,  0, 59, 88, 70,  1, 66, 34, 61]])

In [167]:
arr2[:-3]

array([[18, 53,  0, 59, 88, 70,  1, 66, 34, 61],
       [19, 40, 38,  0, 48, 61, 47, 88, 35, 69],
       [24, 41, 95, 75,  2,  1, 22, 76, 93, 83],
       [53,  5, 42, 58, 14, 36, 66, 43,  3, 55],
       [90, 51, 19, 16, 94, 69, 77, 38, 85, 26],
       [29,  3, 64, 32, 75, 81, 47, 64, 66, 38],
       [80, 82, 13,  7, 86,  1, 27, 80, 91, 92]])

In [168]:
arr

array([0, 1, 2, 3, 4, 5])

In [169]:
arr.max()

np.int64(5)

In [170]:
arr.min()

np.int64(0)

In [171]:
arr.mean()

np.float64(2.5)

In [172]:
arr

array([0, 1, 2, 3, 4, 5])

In [173]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [175]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

In [176]:
arr

array([0, 1, 2, 3, 4, 5])

In [177]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [178]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [182]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [183]:
arr

array([0, 1, 2, 3, 4, 5])

In [184]:
arr.reshape(2, 4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [185]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [186]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [187]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [188]:
arr

array([0, 1, 2, 3, 4, 5])

In [190]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [194]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [195]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [196]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [197]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [198]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [199]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

## Indexing

In [202]:
mat = np.arange(0, 100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [205]:
row = 4
col = 5

In [206]:
row

4

In [207]:
col

5

In [208]:
mat[row, col]

np.int64(45)

In [209]:
mat[4, 5]

np.int64(45)

In [211]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
mat[6] # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [214]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
col = 6

In [217]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [218]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [219]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [220]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [221]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [222]:
row

4

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [225]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [227]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [228]:
row

4

In [229]:
col

6

In [231]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [232]:
mat[1, 4]

np.int64(14)

In [233]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [234]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [235]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [236]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [238]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [240]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [241]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [242]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [243]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [244]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [245]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [246]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [247]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [249]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [250]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [251]:
mat[0,1]

np.int64(1)

In [252]:
mat[1,6]

np.int64(16)

In [258]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [256]:
mat[0,1]

np.int64(1)

In [257]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [259]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [260]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [261]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [262]:
mat[3,5]

np.int64(35)

In [263]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [264]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [265]:
mat[1:2,2:4]

array([[12, 13]])

In [266]:
mat[2:3,2:3]

array([[22]])

In [267]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [268]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [270]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [271]:
mat[2:3,4:5]

array([[24]])

## Masking

In [272]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [273]:
id(mat)

4669805488

In [276]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [280]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [277]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [278]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [279]:
mat[mat==50]

array([50])

In [281]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [282]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [283]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [284]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [286]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [287]:
a4 = mat[mat==50]
a4

array([50])

## python program to generat otp

In [293]:
import random

def generate_otp(length):
    """Generate a numeric OTP of a specified length."""
    digits = '0123456789'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 6  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 029052


In [294]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [295]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [300]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x11692d140>


In [297]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)
print(y)

[1, 2, 3, 4]
[1, 2, 3]
