## 1. Array Creation Functions

In [25]:
import numpy as np

In [26]:
# Create an array from a list
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [27]:
print("Array a:", a)

Array a: [1 2 3 4]


In [28]:
# Create an array with evenly spaced values
b = np.arange(0, 10, 2)
print("Array b:", b)

Array b: [0 2 4 6 8]


In [29]:
# Create an array with linearly spaced values
c = np.linspace(0, 1, 5)
print("Array C:", c)

Array C: [0.   0.25 0.5  0.75 1.  ]


In [30]:
# Create an array filled with zeros
d = np.zeros((2, 3)) # 2x3 array of zeros
print("Arrar D:", d)

Arrar D: [[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
# Create an array filled with ones
e = np.ones((3, 2))  # 3x2 array of ones
print("Array E:", e)

Array E: [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [32]:
# Create an identity matrix
f = np.eye(4) # 4x4 identity matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 2. Array Manipulation Functions

In [33]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (3, 1))  # Reshape to 3x1
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[1]
 [2]
 [3]]


In [34]:
reshaped = np.reshape(a1, (1, 3))  # Reshape to 1x3
print("Reshaped Array:", reshaped)

Reshaped Array: [[1 2 3]]


In [35]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened Array:", flattened)

Flattened Array: [1 2 3 4]


In [36]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [37]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # transposed the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [38]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.stack([a2,b2])
print("Stacked Array:\n", stacked)

Stacked Array:
 [[1 2]
 [3 4]]


## 3. Mathematical Functions

In [39]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g,2)  # add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [40]:
# Square each element
squared = np.pow(g,2)  # square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [41]:
# Square root of each element
sqrt_val = np.sqrt(g) # square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [42]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [43]:
# Dot product of two arrays
a2 = np.array([1, 2 ,3])
dot_product = np.dot(a2, g)  # dot product of a2 and g
print("Dot product of a2 and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [44]:
g=np.array([1, 2, 3])
print(a2)
print(g)
dot_product = np.dot(a2, g)  # dot product of a2 and g
print("Dot product of a2 and g:", dot_product)

[1 2 3]
[1 2 3]
Dot product of a2 and g: 14


## 4. Statistical Functions

In [45]:
# Mean of array
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [46]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [47]:
# Minimum element of array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [48]:
# Maximum element of array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


## 5. Linear Algebra Functions

In [49]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]])
matrix

array([[1, 2],
       [3, 4]])

In [50]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [51]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## 6. Random Sampling Functions

In [52]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3) # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.21406937 0.10020882 0.97680009]


In [53]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [54]:
# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 1
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [55]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 1
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


## 7. Boolean & Logical Functions

In [56]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)
print("All elements True:", all_true)

All elements True: False


In [57]:
# Check if all elements are True
# all
logical_test = np.array([True, True, True])
all_true = np.all(logical_test)
print("All elements True:", all_true)

All elements True: True


In [58]:
# Check if all elements are True
# all
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)
print("All elements True:", all_true)

All elements True: False


In [59]:
# Check if any elements are True
# any
logical_test = np.array([True, False, True])
all_true = np.any(logical_test)
print("Any elements True:", all_true)

Any elements True: True


## 8. Set Operations

In [60]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [61]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


## 9. Array Attribute Functions

In [62]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size  # Number of elements
dimensions = a.ndim  # Number of dimensoins
dtype = a.dtype # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


In [63]:
type(a)

numpy.ndarray

In [64]:
a = np.array([[1, 2], [4, 5], [7, 8]])
shape = a.shape  # Shape of the array
size = a.size  # Number of elements
dimensions = a.ndim  # Number of dimensoins
dtype = a.dtype # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3, 2)
Size of a: 6
Number of dimensions of a: 2
Data type of a: int64


In [65]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
shape = a.shape  # Shape of the array
size = a.size  # Number of elements
dimensions = a.ndim  # Number of dimensoins
dtype = a.dtype # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (2, 2, 2)
Size of a: 8
Number of dimensions of a: 3
Data type of a: int64


## 10. Other Functions

In [66]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [67]:
# Size in bytes of an array
array_size_inbytes = a.nbytes  # Size in bytes
print("Data type of a:", a.dtype)
print("Size of a in bytes", array_size_inbytes)

Data type of a: int64
Size of a in bytes 24


In [68]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a copied_array share memory?", shared)

Do a copied_array share memory? False
